<a href="https://colab.research.google.com/github/arindakhill/My_colab_notes/blob/main/Numpy_pandas_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Libraries

In [79]:
import numpy as np
import pandas as pd
import matplotlib as plt
import sys

import sklearn

import seaborn as sns
from numpy.random import randn


Checking Python version

In [ ]:

sys.version

'3.7.12 (default, Sep 10 2021, 00:21:48) \n[GCC 7.5.0]'

## #NUMPY
#Comparing python lists with numpy arrays
Tutorial url:[here](https://www.youtube.com/watch?v=oxEak3HHUOM)

In [6]:
numpy_array=np.arange(0,1000000)
python_list=range(1000000)

print("Python List")
time=%timeit -r 1 -o sum(python_list)
print(time.all_runs[0]/time.loops)

print("\n"+"numpy array")
time=%timeit -r 1 -o np.sum(numpy_array)
print(time.all_runs[0]/time.loops)

print("\n"+"numpy array -- standard library sum")
time=%timeit -r 1 -o sum(numpy_array)
print(time.all_runs[0]/time.loops)

Python List
10 loops, best of 1: 21.6 ms per loop
0.021564116100000773

numpy array
The slowest run took 6.72 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 1: 718 µs per loop
0.0007177298070000688

numpy array -- standard library sum
10 loops, best of 1: 177 ms per loop
0.1772858117999931


#Numypy NdArrays


*   have types
*   Each array is of one type




In [10]:
ints=np.array(range(3))
chars=np.array(list('ABC'))
strings=np.array(['A','BC',"DEF"])

print(ints.dtype, chars.dtype,strings.dtype)

int64 <U1 <U3


In [11]:
chars

array(['A', 'B', 'C'], dtype='<U1')

In [12]:
strings

array(['A', 'BC', 'DEF'], dtype='<U3')

In [13]:
ints

array([0, 1, 2])

In [15]:
ints*0.3

array([0. , 0.3, 0.6])

In [16]:
(ints*0.3).dtype

dtype('float64')

# Creating and using NdArray

In [22]:
my_lst_ndarray=np.array([1,2,3,4,5],np.int32)
my_tuple_ndarray=np.array((1,2,3,4,5), np.int32)

In [23]:
print(my_lst_ndarray.dtype)
print(my_tuple_ndarray.dtype)

int32
int32


In [20]:
print(my_lst_ndarray.shape)
print(my_tuple_ndarray.shape)

(5,)
(5,)


# 2D arrays

In [22]:
nd_arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,16]])
nd_arr.shape


(3, 5)

#Access info in the Array


*   Individual data
*   Slices of data



In [7]:
nd_arr[0,4]

5

In [13]:
nd_arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [18]:
nd_arr[:,:-3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [15]:
nd_arr[-1:,:-1]

array([[11, 12, 13, 14]])

In [19]:
nd_arr[:-1,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
nd_arr.sum()


121

In [24]:
nd_arr.sum?

In [25]:
nd_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 16]])

In [27]:
nd_arr.sum(axis=1)

array([15, 40, 66])

In [28]:
nd_arr.sum(axis=0)

array([18, 21, 24, 27, 31])

In [30]:
nd_arr.min()

1

In [32]:
nd_arr.min(axis=1)

array([ 1,  6, 11])

In [33]:
nd_arr.min(axis=0)

array([1, 2, 3, 4, 5])

#Broadcasting

In [48]:
a=np.array([10,-10])
b=np.array([5,-5])
c=np.array([0.5,4,1])

In [38]:
a

array([ 10, -10])

In [39]:
b

array([ 5, -5])

In [40]:
c

array([0.5, 4. , 1. ])

In [41]:
a+b

array([ 15, -15])

In [43]:
a*b

array([50, 50])

In [44]:
a/b

array([2., 2.])

In [49]:
a%b

array([0, 0])

In [63]:
a=np.array([[10],[-10]])
b=np.array([[1,2],[2,4]])

In [66]:
print(a)
print('\n')
print(b)
print('\n\n')
print(a+b)
print('\n')
print(a.shape, b.shape)
print('\n\n')
print(a-2)
print('\n\n')
print(b*3)
#Elemenets will "duplicate, expand and fill up"
#to make the dimesions compatible for element-wise operation

[[ 10]
 [-10]]


[[1 2]
 [2 4]]



[[11 12]
 [-8 -6]]


(2, 1) (2, 2)



[[  8]
 [-12]]



[[ 3  6]
 [ 6 12]]


# #**PANDAS**
Pandas series
*   In a nutsell, pandas series are one dimensional np.ndarray vector with **an index**
*   They are built upon Ndarrays



In [70]:
series=pd.Series([100,200,200,np.nan,400])
print(series)
print('\n')
print(series.shape)
print(series.values)

0    100.0
1    200.0
2    200.0
3      NaN
4    400.0
dtype: float64


(5,)
[100. 200. 200.  nan 400.]


In [88]:
dt_index=pd.date_range('2021-1-1','2021-9-1',freq='m')
word_series=pd.Series(["arinda","esther","ethan","ahumuza","hillary","kizza","...",None],index=dt_index)
word_series

2021-01-31     arinda
2021-02-28     esther
2021-03-31      ethan
2021-04-30    ahumuza
2021-05-31    hillary
2021-06-30      kizza
2021-07-31        ...
2021-08-31       None
Freq: M, dtype: object

Dealing with dates

In [74]:
pd.date_range?

In [90]:
#datetime index
dt_index=pd.date_range('2021-1-1','2021-12-30',freq='m')
dt_series=pd.Series(randn(11),index=dt_index)
print(dt_series)
dt_index

2021-01-31    1.138268
2021-02-28    0.007663
2021-03-31    0.755774
2021-04-30    0.419036
2021-05-31   -0.787450
2021-06-30   -1.846620
2021-07-31    0.383173
2021-08-31    1.058882
2021-09-30   -2.391969
2021-10-31    1.399708
2021-11-30    1.272039
Freq: M, dtype: float64


DatetimeIndex(['2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30',
               '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31',
               '2021-09-30', '2021-10-31', '2021-11-30'],
              dtype='datetime64[ns]', freq='M')

In [96]:
dt_series.max()

1.3997083875792882

**Index**

* Notice how each series has an index (in this case a relatively meaningless default index).
* Pandas can make great use of informative indexes. Indexes work similarly to a dictionary key, allowing fast lookups of the data associated with the index.
* Indexes can also be exploited for fast group-bys, merges, time-series operations and lots more.
* When you're really in the zone with pandas, you'll be thinkina a lot about indexes.


# Pandas DataFrames
* A set of series that share the same index

In [98]:
index_a=pd.Series(randn(4),index=(['arinda','hillary','kizza','esther']))

In [99]:
index_b=pd.Series(randn(4),index=['arinda','ethan','ahumuza','esther'])

In [102]:
print(index_a)
print('\n')
print(index_b)
print('\n\n')
print(index_a+index_b)


arinda     0.787186
hillary   -1.206557
kizza     -0.434580
esther    -0.738216
dtype: float64


arinda     0.932561
ethan     -1.197807
ahumuza   -0.841334
esther     1.183043
dtype: float64



ahumuza         NaN
arinda     1.719747
esther     0.444827
ethan           NaN
hillary         NaN
kizza           NaN
dtype: float64


In [105]:
dframe=pd.DataFrame([[1,2,3],[4,5,6]],
                    columns=['arinda','ethan','esther'],
                    index=['a','b'])

In [107]:
print(dframe)

   arinda  ethan  esther
a       1      2       3
b       4      5       6


In [109]:
df=pd.DataFrame(randn(11,5),index=dt_index, columns=[x for x in 'abcde'])

In [110]:
print(df)

                   a         b         c         d         e
2021-01-31  0.346660  0.919220 -0.749978  1.071257 -0.468449
2021-02-28  1.849014 -0.150361  0.329953  1.185514 -0.429099
2021-03-31 -0.310206  0.029114 -0.020804 -0.375147  0.505769
2021-04-30  1.267929  1.615148  0.054196  0.052833  1.129534
2021-05-31  0.152267 -0.780995  0.061850  1.005412  1.973250
2021-06-30  0.498378  1.022751 -1.861467 -1.377795  1.561040
2021-07-31 -0.832364 -1.071818 -0.155693  0.252249 -0.086627
2021-08-31  0.777549  0.925177 -1.425439  1.591463 -1.160788
2021-09-30  1.104116  1.204797 -1.934701 -1.029340  1.788701
2021-10-31  1.407480 -0.130707 -1.194974  0.177555 -0.022225
2021-11-30  0.402656  0.869056  1.519529 -0.336584  0.924336


# Select one column

In [115]:
df['a']

2021-01-31    0.346660
2021-02-28    1.849014
2021-03-31   -0.310206
2021-04-30    1.267929
2021-05-31    0.152267
2021-06-30    0.498378
2021-07-31   -0.832364
2021-08-31    0.777549
2021-09-30    1.104116
2021-10-31    1.407480
2021-11-30    0.402656
Freq: M, Name: a, dtype: float64

Select one column alternative

In [112]:
df.a


2021-01-31    0.346660
2021-02-28    1.849014
2021-03-31   -0.310206
2021-04-30    1.267929
2021-05-31    0.152267
2021-06-30    0.498378
2021-07-31   -0.832364
2021-08-31    0.777549
2021-09-30    1.104116
2021-10-31    1.407480
2021-11-30    0.402656
Freq: M, Name: a, dtype: float64

# To select one row, user loc[]

In [116]:
df.loc['2021-10-31']

a    1.407480
b   -0.130707
c   -1.194974
d    0.177555
e   -0.022225
Name: 2021-10-31 00:00:00, dtype: float64

# A column of  a dataframe is a series


In [127]:
col=df['b']
type(col)

pandas.core.series.Series

# A row of a data frame is also a series

In [125]:
row=df.loc['2021-11-30']
type(row)

pandas.core.series.Series

# colums have the same index

In [128]:
col.index

DatetimeIndex(['2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30',
               '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31',
               '2021-09-30', '2021-10-31', '2021-11-30'],
              dtype='datetime64[ns]', freq='M')

What about rows?

In [129]:
row.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [130]:
df.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [131]:
df.columns.values


array(['a', 'b', 'c', 'd', 'e'], dtype=object)

In [132]:
list(df.columns.values)

['a', 'b', 'c', 'd', 'e']

# Select multiple columns using two brackets

In [135]:
df[['a','b']]

a         b
2021-01-31  0.346660  0.919220
2021-02-28  1.849014 -0.150361
2021-03-31 -0.310206  0.029114
2021-04-30  1.267929  1.615148
2021-05-31  0.152267 -0.780995
2021-06-30  0.498378  1.022751
2021-07-31 -0.832364 -1.071818
2021-08-31  0.777549  0.925177
2021-09-30  1.104116  1.204797
2021-10-31  1.407480 -0.130707
2021-11-30  0.402656  0.869056

# column operations
Operations are broadcast to every element in the column like in numpy

In [136]:
df['a']+df['b']

2021-01-31    1.265879
2021-02-28    1.698654
2021-03-31   -0.281093
2021-04-30    2.883077
2021-05-31   -0.628728
2021-06-30    1.521128
2021-07-31   -1.904182
2021-08-31    1.702726
2021-09-30    2.308912
2021-10-31    1.276773
2021-11-30    1.271712
Freq: M, dtype: float64